### ISSUE TITLE
Failed to start the KeyspaceManager

### ISSUE THREAD

**Issue by rsoika** [elek/docker-hadoop#5]
Hi,
I try to startup the hadoop/ozone cluster as explained here: 
https://cwiki.apache.org/confluence/display/HADOOP/Getting+Started+with+docker

But I got the following error when trying to start:

```
......
ksm_1       | STARTUP_MSG:   build = https://github.com/apache/hadoop.git -r 056a9783337f7e384f651cf86b30abf995d1ead8; compiled by 'elek' on 2017-09-27T19:10Z
ksm_1       | STARTUP_MSG:   java = 1.8.0_121
ksm_1       | ************************************************************/
ksm_1       | 2017-09-29 22:03:33 INFO  KeySpaceManager:51 - registered UNIX signal handlers for [TERM, HUP, INT]
ksm_1       | 2017-09-29 22:03:34 INFO  CallQueueManager:84 - Using callQueue: class java.util.concurrent.LinkedBlockingQueue queueCapacity: 20000 scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler
ksm_1       | 2017-09-29 22:03:34 INFO  Server:1067 - Starting Socket Reader #1 for port 9862
ksm_1       | 2017-09-29 22:03:34 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
ksm_1       | 2017-09-29 22:03:34 ERROR KeySpaceManager:191 - Failed to start the KeyspaceManager.
ksm_1       | java.lang.NullPointerException
ksm_1       | 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
ksm_1       | 	at org.apache.hadoop.ozone.web.utils.OzoneUtils.getScmMetadirPath(OzoneUtils.java:256)
ksm_1       | 	at org.apache.hadoop.ozone.ksm.KSMMetadataManagerImpl.<init>(KSMMetadataManagerImpl.java:71)
ksm_1       | 	at org.apache.hadoop.ozone.ksm.KeySpaceManager.<init>(KeySpaceManager.java:104)
ksm_1       | 	at org.apache.hadoop.ozone.ksm.KeySpaceManager.main(KeySpaceManager.java:187)
ksm_1       | 2017-09-29 22:03:34 INFO  ExitUtil:210 - Exiting with status 1: java.lang.NullPointerException
ksm_1       | 2017-09-29 22:03:34 INFO  KeySpaceManager:51 - SHUTDOWN_MSG: 
ksm_1       | /************************************************************
ksm_1       | SHUTDOWN_MSG: Shutting down KeySpaceManager at 25ef3a8c8827/172.18.0.4
ksm_1       | ************************************************************/
ksm_1       | Process exited with exit code 1
ksm_1       | Process has been failed (exit code: 1), restarting after 60 seconds... (4/10)
......
```

Is there any solution to fix this? It would be great to use docker for testing the hadoop/ozone  feature.

Thanks for any help

**Comment by rsoika** [comment]
I tried it with a newer image but got the same result.
Can anybody give me a hint for this issue?

**Comment by ps-account** [comment]
I bump into similar issues. From your comments it doesn't appear that things are updated here, a better place to comment is to get the containers internal in the apache project, following this issue: https://issues.apache.org/jira/browse/HADOOP-14898

**Comment by elek** [comment]
Sorry, I didn't notice this comment earlier due to the noise/signal ratio in my Github account.

If you are interested about Ozone, you can find example Kubernetes resources inside every Ozone release (which should work) and ask help on https://github.com/apache/hadoop-ozone/blob/master/CONTRIBUTING.md

Flokkr image for Ozone is available at https://github.com/flokkr/docker-ozone and Flekszible based K8s resource definitions are here: https://github.com/elek/ozone-flekszible
